spring.application.name=ems
spring.profiles.active = dev


######################## DATABASE CONFIGURATION ################################
spring.datasource.url = jdbc:postgresql://localhost:5432/EMS
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto = create


########################### SERVER PORT #########################
server.port = 9595
############################ DATABASE LIQUIBASE ###################################
spring.liquibase.change-log = classpath:db/changelog/db.changelog-master.xml

############################ CONTEXT PATH #########################################
server.servlet.context-path = /ems

############################ LOGGING HIBERNATE QUERIES ####################################
logging.level.org.hibernate.SQL = debug

############################ OUTPUT TERMINAL ######################################
spring.output.ansi.enabled = always
